basic.forever(function () {
    basic.pause(1000)
    basic.showNumber(1)
    basic.showNumber(2)
    basic.showNumber(3)
    basic.showNumber(4)
    basic.showNumber(5)
    basic.showNumber(6)
    basic.showNumber(7)
    basic.showNumber(8)
    basic.showNumber(9)
    basic.showNumber(10)
    basic.pause(1000)
    basic.showIcon(IconNames.Heart)
    music.playMelody("C5 B G A A F D C ", 120)
    basic.showString("I  LOVE SOU  MUCH  MI  FAMILIE")
    basic.showString("THANK  YOU")
    music.playMelody("C5 A F D G B D C ", 120)
    basic.showIcon(IconNames.Happy)
})
